WEB/Controllers/RequestController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net.Http;
using System.Net.Http.Headers;
using System.Net.Mail;
using System.Web;
using System.Web.Mvc;
using MySql.Data.MySqlClient;
using WEB.Models;

namespace WEB.Controllers
{

    public class RequestController : Controller
    {
        MySql.Data.MySqlClient.MySqlConnection dbConn = new MySql.Data.MySqlClient.MySqlConnection(
            "server=localhost;user id=root;password=V4Vendetta;database=leviomap");

        public ActionResult Index() 
        {
            IEnumerable<RequestModel> requestList;
            HttpClient client = new HttpClient();
            client.BaseAddress = new Uri("http://localhost:18080/map-web/map/User/");
            client.DefaultRequestHeaders.Accept.Add(new MediaTypeWithQualityHeaderValue("application/json"));
            HttpResponseMessage response = client.GetAsync("getAllRequests").Result;
            try
            {
                    requestList = response.Content.ReadAsAsync<IEnumerable<RequestModel>>().Result;

            }
            catch (AggregateException e)
            {

                Console.WriteLine(e);
                throw;
            }
         
            return View(requestList);
        }

        [HttpPost]
        public ActionResult Delete(int id)
        {
            HttpClient client = new HttpClient();
            client.BaseAddress = new Uri("http://localhost:18080/map-web/map/client/");
            HttpResponseMessage response = client.GetAsync("DeleteRequest?id=" + id).Result;
            return RedirectToAction("Index");

        }
        [HttpPost]
        public ActionResult DeleteTreatedRequests()
        {
            HttpClient client = new HttpClient();
            client.BaseAddress = new Uri("http://localhost:18080/map-web/map/User/");
            HttpResponseMessage response = client.GetAsync("deleteTreatedRequets").Result;
            return RedirectToAction("Index");

        }

          [HttpPost]
        public ActionResult TreatRequest(int id)
        {
            HttpClient client = new HttpClient();
            client.BaseAddress = new Uri("http://localhost:18080/map-web/map/User/");
            HttpResponseMessage response = client.GetAsync("treatClientRequest?requestId="+id).Result;
            return RedirectToAction("Index");

        }

        [HttpPost]
        public ActionResult AddClientRequest(String resource, String project, DateTime projectDate)
        {
            MySqlCommand cmd = dbConn.CreateCommand();
            cmd.CommandText =
                "INSERT into request (context, deliveryDate, resourceType, status) VALUES (@project, @delivery, @resource, @status)";
            cmd.Parameters.AddWithValue("@project", project);
            cmd.Parameters.AddWithValue("@delivery", projectDate);
            cmd.Parameters.AddWithValue("@resource", resource);
            cmd.Parameters.AddWithValue("@status", 0);

            try
            {
                dbConn.Open();
            }
            catch (Exception erro)
            {
                Console.WriteLine(erro);


            }
            cmd.ExecuteNonQuery();            
            cmd.CommandText =
                "INSERT into client_request  VALUES (2, (select id from request order by id desc limit 1))";
            cmd.ExecuteNonQuery();
            return RedirectToAction("AddClientRequest");
        }


        [HttpGet]
        public ActionResult AddClientRequest()
        {
            List<ProjectModel> listeProject = new List<ProjectModel>();
            MySqlCommand cmd1 = dbConn.CreateCommand();
            cmd1.CommandText = "select id,name from project";
            try
            {
                dbConn.Open();
            }
            catch (Exception erro)
            {
                Console.WriteLine(erro);
            }

            MySqlDataReader reader = cmd1.ExecuteReader();

            while (reader.Read())
            {
                ProjectModel projectmodel = new ProjectModel();
                projectmodel.id = Convert.ToInt32(reader.GetValue(0));
                projectmodel.name = Convert.ToString(reader.GetValue(1));
                listeProject.Add(projectmodel);
            }
            reader.Close();
            return View(listeProject);
        }

        [HttpGet]
        public ActionResult viewClientRequests()
        {
            List<RequestModel> listeRequest = new List<RequestModel>();
            MySqlCommand cmd1 = dbConn.CreateCommand();
            cmd1.CommandText = "select * from request where id in (select requests_id from client_request where clients_id = 2)";
            try
            {
                dbConn.Open();
            }
            catch (Exception erro)
            {
                Console.WriteLine(erro);
            }

            MySqlDataReader reader = cmd1.ExecuteReader();

            while (reader.Read())
            {
                RequestModel requestmodel = new RequestModel();
                requestmodel.id = Convert.ToInt32(reader.GetValue(0));
                requestmodel.context = Convert.ToString(reader.GetValue(1));
                requestmodel.deliveryDate = Convert.ToDateTime(reader.GetValue(2));
                requestmodel.resourceType = Convert.ToString(reader.GetValue(3));
                requestmodel.status = (Convert.ToInt32(reader.GetValue(4)) == 0 ? false : true);
                listeRequest.Add(requestmodel);
            }
            reader.Close();
            return View(listeRequest);
        }



        [HttpGet]
        public ActionResult deleteClientRequest(int id)
        {
            MySqlCommand cmd1 = dbConn.CreateCommand();
            cmd1.CommandText = "delete from client_request where clients_id = 2 and requests_id = @id ";
            cmd1.Parameters.AddWithValue("@id", id);
            try
            {
                dbConn.Open();
            }
            catch (Exception erro)
            {
                Console.WriteLine(erro);
            }

            cmd1.ExecuteNonQuery();
            cmd1.CommandText = "delete from request where id = @id";
            cmd1.ExecuteNonQuery();
            return RedirectToAction("viewClientRequests");
        }

    }

}

WEB/Views/Request/AddClientRequest.cshtml
@model List<WEB.Models.ProjectModel>

@{
    ViewBag.Title = "AddClientRequest";
    Layout = "~/Views/Shared/_DashboardLayout.cshtml";
}
@section Css
{
    <link href="~/Content/css/sweetalert2.min.css" rel="stylesheet" />
<link href="~/Content/vendors/css/base/elisyam-1.5.min.css" rel="stylesheet" />
<link href="~/Content/css/animate/animate.min.css" rel="stylesheet" />
}
<div class="container-fluid">
    <!-- Begin Page Header-->
    <div class="row">
        <div class="page-header">
            <div class="d-flex align-items-center">
                <h2 class="page-header-title">Requests</h2>

            </div>
        </div>
    </div>
    <!-- End Page Header -->

    <div class="row flex-row">
        <div class="col-xl-12">

            <!-- Form -->
            <div class="widget has-shadow">
                <div class="widget-header bordered no-actions d-flex align-items-center">
                    <h4>Add New Request</h4>
                </div>
                <br/><br/>
                <div class="form-group row d-flex align-items-center mb-5">
                    <label class="col-lg-4 form-control-label d-flex justify-content-lg-end">Resource Type</label>
                    <div class="col-lg-5">
                        <div class="select">
                            <select name="account" class="custom-select form-control resource" required="">
                                <option value="">Select an option</option>
                                <option>Employee</option>
                                <option>Freelancer</option>

                            </select>
                            <div class="invalid-feedback">
                                Please select an option
                            </div>
                        </div>
                    </div>
                </div>



                        <div class="form-group row d-flex align-items-center mb-5">
                            <label class="col-lg-4 form-control-label d-flex justify-content-lg-end ">Delivery Date</label>
                            <div class="col-lg-5">
                                <input type="date" class="form-control delivery" placeholder="MM/DD/YYYY">
                            </div>
                        </div>
                        <div class="form-group row d-flex align-items-center mb-5">
                            <label class="col-lg-4 form-control-label d-flex justify-content-lg-end">Concerned Project</label>
                            <div class="col-lg-5">
                                <div class="select">
                                    <select name="account" class="custom-select form-control project" required="">
                                        <option value="">Select an option</option>
                                        @foreach (var m in Model)
                                        {
                                            <option id="@m.id">@m.name</option>
                                        }
                                        </select>
                                    <div class="invalid-feedback">
                                        Please select an option
                                    </div>
                                </div>
                            </div>
                        </div>


                        <div class="em-separator separator-dashed"></div>


                        <div class="text-right">
                            <a class="btn btn-gradient-01" style="margin-bottom: 30px; margin-right: 20px;" >Send Request</a>

                        </div>
                </div>
            </div>
            <!-- End Form -->
        </div>
    </div>
    <!-- End Row -->
@section JavaScript
{
    <script src="../../Content/vendors/js/noty/noty.min.js"></script>
    <script src="~/Scripts/bootstrap.min.js"></script>
    <script type="text/javascript" src="https://cdn.datatables.net/1.10.12/js/jquery.dataTables.min.js"></script>
    <script type="text/javascript" src="https://cdn.datatables.net/buttons/1.2.2/js/dataTables.buttons.min.js"></script>
    <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/jszip/2.5.0/jszip.min.js"></script>
    <script type="text/javascript" src="https://cdn.rawgit.com/bpampuch/pdfmake/0.1.18/build/pdfmake.min.js"></script>
    <script type="text/javascript" src="https://cdn.rawgit.com/bpampuch/pdfmake/0.1.18/build/vfs_fonts.js"></script>
    <script type="text/javascript" src="https://cdn.datatables.net/buttons/1.2.2/js/buttons.html5.min.js"></script>
    <script src="~/Content/js/sweetalert2.min.js"></script>

    <script>
        $(document).ready(function () {
            $('.btn.btn-gradient-01').on('click',
                function (a) {
                    a.preventDefault();
                    var resource = $('.resource option:selected').text();
                    var project = $('.project option:selected').text();
                    var projectDate = $('.delivery').val();
                    console.log(resource + " " + project + " " + projectDate);
                    $.ajax({
                        type: "post",
                        url: '@Url.Action("AddClientRequest", "Request")',
                        data: "resource=" + resource + "&project=" + project + "&projectDate=" + projectDate,
                        cache: false,
                        success: function(e) {
                            new Noty({
                                type: 'success',
                                layout: 'topRight',
                                text: 'Request Has Been Sent Successfully',
                                progressBar: true,
                                timeout: 2500,
                                animation: {
                                    open: 'animated bounceInRight', // Animate.css class names
                                    close: 'animated bounceOutRight' // Animate.css class names
                                }
                            }).show();
                            for (var i = 0; i < 1000; i+=2) {
                                i -= 1;
                            }
                            window.location.href = '@Url.Action("viewClientRequests", "Request")';

                        }

                    });
                });

        });
    </script>
}

WEB/Views/Request/Index.cshtml
@model IEnumerable<WEB.Models.RequestModel>

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_DashboardLayout.cshtml";
}

@section Css
{
    <link href="~/Content/alertifyjs/alertify.min.css" rel="stylesheet" />
    <link rel="stylesheet" href="https://cdn.datatables.net/1.10.19/css/jquery.dataTables.min.css" />
    <link rel="stylesheet" href="https://cdn.datatables.net/buttons/1.5.1/css/buttons.dataTables.min.css" />
<link href="~/Content/css/request.css" rel="stylesheet" />
    <link href="~/Content/css/sweetalert2.min.css" rel="stylesheet" />
    <link href="~/Content/vendors/css/base/elisyam-1.5.min.css" rel="stylesheet" />
    <link href="~/Content/css/animate/animate.min.css" rel="stylesheet" />
}


<div class="row">
    <div class="col-xl-12">
        <!-- Hover -->
        <div class="widget has-shadow">
            <div class="widget-header bordered no-actions d-flex align-items-center">

                <h2>Requests List</h2>
                <a class="btn btn-success removeTreated" style="color: white !important">Remove Treated Requests</a>
            </div>
            <div class="widget-body">
                <div class="table-responsive">
                    <table id="exportable"class="table table-hover mb-0">
                        <thead>
                            <tr>
                                <th>Subject</th>
                                <th>Delivery Date</th>
                                <th>Resource Type</th>
                                <th><span style="width:100px;">Status</span></th>
                                <th>Actions</th>
                            </tr>
                        </thead>
                        <tbody>
                            @{ var currentStatus = false;}
                            @foreach (var item in Model)
                            {
                                <tr>
                                    <td><span class="text-primary">@Html.DisplayFor(modelItem => item.context)</span></td>
                                    <td>@Html.DisplayFor(modelItem => item.deliveryDate)</td>
                                    <td>@Html.DisplayFor(modelItem => item.resourceType)</td>
                                    @if (item.status != null)
                                    {

                                        if (item.status == false)
                                        {
                                            currentStatus = false;
                                            <td><span style='width: 100px;'><span class='badge-text badge-text-small info'>Opened</span></span></td>
                                        }
                                        else
                                        {
                                            currentStatus = true;
                                            <td><span style='width: 100px;'><span class='badge-text badge-text-small danger'>Closed</span></span></td>
                                        }
                                    }
                                    else
                                    {
                                        <td>@Html.DisplayFor(modelItem => item.status)</td>

                                    }
                                    <td class="td-actions">
                                        @if (currentStatus)
                                        {
                                            <a><i class="la la-close delete disabled" data-value="@item.id"></i></a>

                                        }
                                        else
                                        {   <a><i class="la la-check edit" data-value="@item.id"></i></a>

                                        }
                                        <a><i class="la la-trash delete" data-value="@item.id"></i></a>
                                    </td>
                                </tr>
                            }
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
        <!-- End Hover -->
    </div>
</div>
<script src="~/Scripts/alertify.js"></script>
<script src="../../Content/vendors/js/noty/noty.min.js"></script>
<script src="../../Content/vendors/js/nicescroll/nicescroll.min.js"></script>
<script src="../../Content/vendors/js/base/core.min.js"></script>
<script src="../../Content/vendors/js/base/jquery.min.js"></script>
<script src="../../Content/vendors/js/nicescroll/nicescroll.min.js"></script>
<script>
    $(document).ready(function () {

        $('.la.la-close.delete.disabled').on('click', function () {
            alert('Action Forbidden! request is already treated');
        });
        $('.la.la-trash.delete').on('click',
            function () {
                var currentElement = $(this).closest('tr');
                var id = $(this).attr('data-value');

                var swalWithBootstrapButtons = swal.mixin({
                    confirmButtonClass: 'btn btn-success',
                    cancelButtonClass: 'btn btn-danger',
                    buttonsStyling: false,
                })


                swalWithBootstrapButtons({
                    title: 'Are you sure you want to delete this request?',
                    text: "",
                    type: 'warning',
                    showCancelButton: true,
                    confirmButtonText: 'Yes, delete it!',
                    cancelButtonText: 'No, cancel!',
                    reverseButtons: true
                }).then((result) => {
                    if (result.value) {
                            $.ajax({
                                type: 'post',
                                url: '@Url.Action("Delete","Request")',
                                data: 'id=' + id,
                                cache: false,
                                success: function (e) {
                                    currentElement.remove();
                                    new Noty({
                                        type: 'success',
                                        layout: 'topRight',
                                        text: 'Request Has Been Deleted Successfully',
                                        progressBar: true,
                                        timeout: 2500,
                                        animation: {
                                            open: 'animated bounceInRight', // Animate.css class names
                                            close: 'animated bounceOutRight' // Animate.css class names
                                        }
                                    }).show();
                                    for (var i = 0; i < 1000; i += 2) {
                                        i -= 1;
                                    }
                                    window.location.reload();
                                    /*   swalWithBootstrapButtons(
                                           'Deleted!',
                                           'Request has been deleted! ',
                                           'success'
                                       );*/

                                }
                            });

                    }
                    else if (result.dismiss === swal.DismissReason.cancel) {
                        swalWithBootstrapButtons(
                            'Cancelled',
                            'Delete has been canceled ',
                            'error'
                        );
                    }
                    });
            });
        $('.removeTreated').on('click',
            function () {
                $.ajax({
                    type: 'post',
                    url: '@Url.Action("DeleteTreatedRequests","Request")',
                    cache: false,
                    success: function (e) {
                        $('.badge-text-small.danger').closest('tr').remove();
                        window.location.reload(true);
                    }
                });
            });
        $('.la.la-check.edit').on('click',
            function () {
                var currentRow = $(this).parent().parent().parent();
                var id = $(this).attr('data-value');
                var currentElement = $(this);
                $.ajax({
                    type: 'post',
                    url: '@Url.Action("TreatRequest", "Request")', 
                    data: 'id='+ id,
                    cache: false, 
                    success: function(e) {
                        currentElement.attr('class', 'la la-close delete');
                        currentRow.children('td:eq(3)').html("<span style='width: 100px;'><span class='badge-text badge-text-small danger'>Closed</span></span>");
                    }
                });
            });


        $('#exportable').DataTable({
            dom: 'Bfrtip',
            buttons: [{
                    extend: 'excel',
                    text: 'Excel',
                    className: 'exportExcel',
                    filename: 'Test_Excel',
                    exportOptions: { modifier: { page: 'all' } }
                },
                {
                    extend: 'csv',
                    text: 'CSV',
                    className: 'exportExcel',
                    filename: 'Test_Csv',
                    exportOptions: { modifier: { page: 'all' } }
                },
                {
                    extend: 'pdf',
                    text: 'PDF',
                    className: 'exportExcel',
                    filename: 'Test_Pdf',
                    exportOptions: { modifier: { page: 'all' } }
                }]
        });
        if ($('#exportable tr').length == 2 && $('.dataTables_empty').text() === "No data available in table") {
            $('.dt-buttons').attr('class', 'flexDiv');
            $('.dt-button.buttons-html5').attr('class', 'btn btn-primary disabled');
            $('.btn.btn-success.removeTreated').attr('class', 'btn btn-success removeTreated disabled');


        } else {
            $('.dt-buttons').attr('class', 'flexDiv');
            $('.dt-button.buttons-html5').attr('class', 'btn btn-primary');
        }
        $('.dataTables_filter input').attr('style', 'border-radius: 8px;');


    });


</script>
<script src="https://ajax.googleapis.com/ajax/libs/webfont/1.6.26/webfont.js"></script>
<script>
    WebFont.load({
        google: { "families": ["Montserrat:400,500,600,700", "Noto+Sans:400,700"] },
        active: function () {
            sessionStorage.fonts = true;
        }
    });
</script>
<script src="~/Scripts/bootstrap.min.js"></script>
<script type="text/javascript" src="https://cdn.datatables.net/1.10.12/js/jquery.dataTables.min.js"></script>
<script type="text/javascript" src="https://cdn.datatables.net/buttons/1.2.2/js/dataTables.buttons.min.js"></script>
<script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/jszip/2.5.0/jszip.min.js"></script>
<script type="text/javascript" src="https://cdn.rawgit.com/bpampuch/pdfmake/0.1.18/build/pdfmake.min.js"></script>
<script type="text/javascript" src="https://cdn.rawgit.com/bpampuch/pdfmake/0.1.18/build/vfs_fonts.js"></script>
<script type="text/javascript" src="https://cdn.datatables.net/buttons/1.2.2/js/buttons.html5.min.js"></script>
<script src="~/Content/js/sweetalert2.min.js"></script>